Feature: Out-of-office Mailagent
fhelfer/ILIAS pull request #1
Opened 2022-06-24 07:59 UTC by fhelfer

2022-06-24 11:26 UTC, fhelfer commented
@mjansenDatabay kannst du hier mal schauen wenn du Zeit hast, ob das nicht einfacher geht?
Ein Test ist fehlgeschlagen wegen der neuen Zeile https://github.com/fhelfer/ILIAS/blob/404bddc595b3bdc272e803377d2619237a914334/Services/Mail/classes/class.ilMail.php#L655
deswegen hab ich da ein bisschen mocken müssen

Der Test läuft damit durch aber ich habe nicht geschaut ob der Test an sich noch Sinn macht (also richtig testet)

2022-06-28 06:55 UTC, mjansenDatabay commented on Services/Mail/classes/class.ilMail.php
> +    protected $loginByUsrIdCallable;
```suggestion
    /** @var callable */
    protected $loginByUsrIdCallable;
```

2022-06-28 06:55 UTC, mjansenDatabay commented on Services/Mail/classes/class.ilMail.php
>      protected $usrIdByLoginCallable;
```suggestion
    /** @var callable */
    protected $usrIdByLoginCallable;
```

2022-06-28 07:04 UTC, mjansenDatabay commented on Services/Mail/classes/class.ilMail.php
> +                /** @var $mail_options ilMailOptions */
Würde ich hier entfernen und oben das Array anders auszeichen (s.o.).

2022-06-28 07:04 UTC, mjansenDatabay commented on Services/Mail/classes/class.ilMail.php
> +    protected array $auto_responder_data = [];
```suggestion
    /** @var array<int, ilMailOptions> */
    protected array $auto_responder_data = [];
```

2022-06-28 07:04 UTC, mjansenDatabay commented on Services/Mail/classes/class.ilMail.php
> +            $c = $this->loginByUsrIdCallable;
```suggestion
```

2022-06-28 07:04 UTC, mjansenDatabay commented on Services/Mail/classes/class.ilMail.php
> +                    $c($this->user_id),
```suggestion
                    ($this->loginByUsrIdCallable)($this->user_id),
```

2022-06-28 07:04 UTC, mjansenDatabay commented on Services/Mail/classes/class.ilMailOptions.php
> +            $this->getAbsentUntil() &&
Ich weiß, dass Du das aus dem Patch so übernommen hast.

Wir sollten from und until gleich behandeln, d.h. entweder beide gegen `> 0` prüfen oder einfach auf einen nach `true` evaluierenden Wert (wie aktuell bei until).

2022-06-28 10:32 UTC, mjansenDatabay commented on Services/Mail/classes/class.ilMail.php
> +    public function setAutoResponderStatus(bool $auto_responder_status) : void
Statt des `Setters` wäre ich für:

- enableAutoresponder() : void
- disableAutoresponder() : void

Gut wäre, wenn die Funktionen die `Immutability` fördern würden und auf der Property eines Clones agieren würden. Dann müsste man beim Aufruf natürlich `$mail = $mail->enableAutorespondeR();` ausführen.

Wenn der Zustand dann intern gesetzt werden soll, müsste mann dann entweder eine private Methode mit  Zustandsmodifikation ergänzen oder direkt die Property auf den gewünschten Wert setzen.

2022-06-28 10:32 UTC, mjansenDatabay commented on Services/Mail/classes/class.ilMail.php
> +    public function getAutoResponderStatus() : bool
Würde ich umbenennen in: `isAutoResponderEnabled() : bool`.

2022-06-28 14:39 UTC, mjansenDatabay commented on Services/Mail/classes/class.ilMail.php
>                      $mail_options->getAbsenceAutoResponderSubject(),
Das würde ich noch anders machen. Da wir uns gerade *in* der Instanz bewegen, würde ich hier einfach die Property auf `false` setzen, ohne über den `Mutator` zu gehen. D.h. einfach hier überall `$this` benutzen.

2022-06-29 08:27 UTC, mjansenDatabay commented on Services/Mail/test/ilMailOptionsTest.php
> +        $clockService = $this->getMockBuilder(ClockInterface::class)->disableOriginalConstructor()->getMock();
```suggestion
        $clockService = $this->getMock(ClockInterface::class);
```

Bei Interfaces ist die Mock-Erstellung wie vorgeschlagen ausreichend.

2022-06-29 11:48 UTC, mjansenDatabay approved these changes

2022-07-21 06:54 UTC, mjansenDatabay requested changes

2022-07-21 06:54 UTC, mjansenDatabay commented on Services/Mail/classes/AutoResponder/class.ilAutoResponderDatabaseRepository.php
> +                new DateTimeImmutable($row['send_time'])
If we pass a datetime string without any timezone information, this is interpreted as "related to `date_default_timezone_get()`".

2022-07-21 06:54 UTC, mjansenDatabay commented on Services/Mail/classes/AutoResponder/class.ilAutoResponderDatabaseRepository.php
> +                new DateTimeImmutable($row['send_time'])
If we pass a datetime string without any timezone information, this is interpreted as "related to `date_default_timezone_get()`".

2022-07-21 06:54 UTC, mjansenDatabay commented on Services/Mail/classes/AutoResponder/class.ilAutoResponderDatabaseRepository.php
> +            new DateTimeImmutable($row['send_time'])
If we pass a datetime string without any timezone information, this is interpreted as "related to `date_default_timezone_get()`".

2022-07-21 06:54 UTC, mjansenDatabay commented on Services/Mail/classes/AutoResponder/class.ilAutoResponderDatabaseRepository.php
> +                'send_time' => ['timestamp', $auto_responder->getSendTime()->format('Y-m-d H:i:s')]
We will lose timezone information here. If we don't want to store this, we could either:

- Explicitly use `UTC` here (which should be documented in the `README.md` of the `Mail` component)
- Store a unix timestamp (`integer`)

2022-07-21 06:54 UTC, mjansenDatabay commented on Services/Mail/classes/AutoResponder/class.ilAutoResponderRepository.php
> +}
Please apply the `PHP-CS-FIXER` to all changed PHP files.

2022-07-21 06:54 UTC, mjansenDatabay commented on Services/Mail/classes/AutoResponder/class.ilAutoResponderDatabaseRepository.php
> +        global $DIC;
This class should not rely on `global $DIC`. Please pass an `ilDBInterface` as a constructor dependency. Of course we have to decide how to create the repository with the database adapter.

We should create a global `mail()` service and make it accessible in the `DIC` (`\ILIAS\DI\Container`) similar to the other components. Maybe we could also get rid of `\ilInitialisation::initMail.

2022-07-21 06:54 UTC, mjansenDatabay commented on Services/Mail/classes/AutoResponder/class.ilAutoResponderRepository.php
> +    public function findBySenderId(int $sender_id) : array;
Please use `PHPDocs` to describe the shape of the array. Or event better. Don't use an array at all, but instead create a `AutoResponderCollection` (or use a similar/better name).

2022-07-21 06:54 UTC, mjansenDatabay commented on Services/Mail/classes/AutoResponder/class.ilAutoResponderRepository.php
> +    public function findByReceiverId(int $receiver_id) : array;
Please use `PHPDocs` to describe the shape of the array. Or event better. Don't use an array at all, but instead create a `AutoResponderCollection` (or use a similar/better name).

2022-07-21 06:54 UTC, mjansenDatabay commented on Services/Mail/classes/AutoResponder/class.ilAutoResponder.php
> +class ilAutoResponder
We should use PHP namespaces and get rid of the `il` prefix.

2022-07-21 06:54 UTC, mjansenDatabay commented on Services/Mail/classes/AutoResponder/class.ilAutoResponderDatabaseRepository.php
> +class ilAutoResponderDatabaseRepository implements ilAutoResponderRepository
We should use PHP namespaces and get rid of the `il` prefix.

2022-07-21 06:54 UTC, mjansenDatabay commented on Services/Mail/classes/AutoResponder/class.ilAutoResponderRepository.php
> +interface ilAutoResponderRepository
We should use PHP namespaces and get rid of the `il` prefix.

2022-07-21 06:54 UTC, mjansenDatabay commented on Services/Mail/classes/AutoResponder/class.ilAutoResponderService.php
> +interface ilAutoResponderService
We should use PHP namespaces and get rid of the `il` prefix.

2022-07-21 06:54 UTC, mjansenDatabay commented on Services/Mail/classes/AutoResponder/class.ilAutoResponderServiceImpl.php
> +class ilAutoResponderServiceImpl implements ilAutoResponderService
We should use PHP namespaces and get rid of the `il` prefix.

2022-07-21 06:54 UTC, mjansenDatabay commented on Services/Mail/classes/AutoResponder/class.ilAutoResponderServiceImpl.php
> +                        (new DateTimeImmutable('NOW'))->sub(new DateInterval('P' . $this->global_idle_time_interval . 'D'))
Please use the `Clock` data type available in `src/Data` to receive `now`. This factory should be a dependency of this service and injected in the constructor.

2022-07-21 06:54 UTC, mjansenDatabay commented on Services/Mail/classes/AutoResponder/class.ilAutoResponderServiceImpl.php
> +                    new DateTimeImmutable('NOW'),
Please use the `Clock` data type available in `src/Data` to receive `now`. This factory should be a dependency of this service and injected in the constructor.

2022-07-21 06:54 UTC, mjansenDatabay commented on Services/Mail/classes/AutoResponder/class.ilAutoResponderServiceImpl.php
> +    protected array $auto_responder_data;
Could you please specify the shape of the array by using `PhpDoc` comments, if possible?

2022-07-21 06:54 UTC, mjansenDatabay commented on Services/Mail/classes/AutoResponder/class.ilAutoResponderServiceImpl.php
> +                $auto_responder->setSendtime(new DateTimeImmutable('NOW'));
Please use the `Clock` data type available in `src/Data` to receive `now`. This factory should be a dependency of this service and injected in the constructor.

2022-07-21 06:54 UTC, mjansenDatabay commented on Services/Mail/classes/Setup/class.ilMailDatabaseUpdateSteps.php
> - *
IMO we MUST NOT change the license header. I know that `PhpStorm` automatically formats it, but this is wrong.

2022-07-21 06:54 UTC, mjansenDatabay commented on Services/Mail/test/ilAutoResponderServiceTest.php
> + * This file is part of ILIAS, a powerful learning management system
The license header is wrong. I know that `PhpStorm` automatically formats it, but this is wrong.

2022-07-21 06:54 UTC, mjansenDatabay commented on Services/Mail/classes/AutoResponder/class.ilAutoResponderServiceImpl.php
> + * This file is part of ILIAS, a powerful learning management system
The license header is wrong. I know that `PhpStorm` automatically formats it, but this is wrong.

2022-07-21 06:54 UTC, mjansenDatabay commented on Services/Mail/classes/AutoResponder/class.ilAutoResponderService.php
> +/**
The license header is wrong. I know that `PhpStorm` automatically formats it, but this is wrong.

2022-07-21 06:54 UTC, mjansenDatabay commented on Services/Mail/classes/AutoResponder/class.ilAutoResponderRepository.php
> + * This file is part of ILIAS, a powerful learning management system
The license header is wrong. I know that `PhpStorm` automatically formats it, but this is wrong.

2022-07-21 06:54 UTC, mjansenDatabay commented on Services/Mail/classes/AutoResponder/class.ilAutoResponderDatabaseRepository.php
> +/**
The license header is wrong. I know that `PhpStorm` automatically formats it, but this is wrong.

2022-07-21 06:54 UTC, mjansenDatabay commented on Services/Mail/classes/AutoResponder/class.ilAutoResponder.php
> + * This file is part of ILIAS, a powerful learning management system
The license header is wrong. I know that `PhpStorm` automatically formats it, but this is wrong.

2022-07-21 09:12 UTC, mjansenDatabay commented on Services/Mail/classes/AutoResponder/class.ilAutoResponderDatabaseRepository.php
> +    public function read(ilAutoResponder $auto_responder) : ilAutoResponder
Do we really need the `read` method?

2022-08-02 11:02 UTC, closed without merging